/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.screens;
import com.baseActions.AttendanceTrack;
import com.baseActions.BenefitsCalculator;
import com.baseActions.EmpActions;
import com.baseActions.EmpAllowances;
import com.baseActions.EmpAttendance;
import com.baseActions.EmpDeductions;
import com.baseActions.EmpDetails;
import com.baseActions.WorkHoursCalculator;
import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;

import javax.swing.JFrame;
/**
 *
 * @author JD Morales
 */
public class JFrameEmpPayroll extends javax.swing.JFrame {

    private int id =0;
    private EmpDetails empDetails;
    private Iterable<EmpDetails> filteredList;
    Calendar cal = new GregorianCalendar();
    int currentYear = cal.get(Calendar.YEAR);
    int selectedMonth = cal.get(Calendar.MONTH);

    float basicSalary = (float) 0.00;
    float grossSalary = (float) 0.00;
    float netSalary = (float) 0.00;
    long hourlyRate = (long) 0.00;
    
    long MinutesWorked = (long) 0.00;
    long OvertimeMinutes = (long) 0.00;
    long UndertimeMinutes = (long) 0.00;

    float totalAllowances = (float) 0.00;
    float totalDeductions = (float) 0.00;

    public JFrameEmpPayroll(int empID, int selectedMonth, int currentYear) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        jButtonHome.setBackground(new Color(99, 93, 255));
        jButtonHome.setForeground(new Color(255, 255, 255));
        jButtonPayroll1.setBackground(new Color(255, 255, 255));
        jButtonPayroll1.setForeground(new Color(0, 0, 0));
        
        this.id = empID;
        this.selectedMonth = selectedMonth;
        this.currentYear = currentYear;

        // Load Work Hours for the employee ID within a selected month of the year
        
        loadEmpDetails(empID);
        jLabelCurrentYear.setText(String.valueOf(currentYear));
        jComboMonth.setSelectedIndex(selectedMonth);
        
        // Get the basic salary and hourly rate
        this.totalAllowances = calcEmpAllowances(empID);
        
        // Get the calculated hours (or minutes) worked for the chosen month
        // Added 1 to the SelectedIndex because arrays start with 0.
        loadWorkHours(empID, jComboMonth.getSelectedIndex()+1, currentYear);

        // Get the Gross Salary
        this.grossSalary = calcGrossSalary(basicSalary, hourlyRate, MinutesWorked, OvertimeMinutes, UndertimeMinutes);
        
        // Get the Deductions
        this.totalDeductions = calcEmpDeductions(empID, this.grossSalary);
        
        // Get the Net Salary
        this.netSalary = calcNetSalary(this.grossSalary, this.totalAllowances, this.totalDeductions);
        
    }    
    
    public JFrameEmpPayroll() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        jButtonHome.setBackground(new Color(99, 93, 255));
        jButtonHome.setForeground(new Color(255, 255, 255));
        jButtonPayroll1.setBackground(new Color(255, 255, 255));
        jButtonPayroll1.setForeground(new Color(0, 0, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        labelCompany = new java.awt.Label();
        labelLogo = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanelNavHome = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonPayroll1 = new javax.swing.JButton();
        jPanelEmpProfile = new javax.swing.JPanel();
        jLabelLastName = new javax.swing.JLabel();
        jTextField1LastName = new javax.swing.JTextField();
        jLabelFirstName = new javax.swing.JLabel();
        jTextField2FirstName = new javax.swing.JTextField();
        jButtonBackButton = new javax.swing.JButton();
        jLabel3EmpNo = new javax.swing.JLabel();
        jTextFieldEmpNo = new javax.swing.JTextField();
        jLabelPhoneNo = new javax.swing.JLabel();
        jTextFieldPhoneNo = new javax.swing.JTextField();
        jLabelSSS = new javax.swing.JLabel();
        jTextFieldSSS = new javax.swing.JTextField();
        jLabelPhilHealth = new javax.swing.JLabel();
        jTextFieldPhilHealth = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabelTIN = new javax.swing.JLabel();
        jTextFieldTIN = new javax.swing.JTextField();
        jLabelPagIbig = new javax.swing.JLabel();
        jTextFieldPAGIBIG = new javax.swing.JTextField();
        jLabel3Position = new javax.swing.JLabel();
        jTextFieldPosition = new javax.swing.JTextField();
        jPanelPayroll = new javax.swing.JPanel();
        jPanelEmpTimesheet = new javax.swing.JPanel();
        jLabelHoursWorked = new javax.swing.JLabel();
        jLabelOvertimeHours = new javax.swing.JLabel();
        jLabelUndertimeHours = new javax.swing.JLabel();
        jTextFieldHoursWorked = new javax.swing.JTextField();
        jTextFieldOvertimeHours = new javax.swing.JTextField();
        jTextFieldUndertimeHours = new javax.swing.JTextField();
        jPanelDeductions = new javax.swing.JPanel();
        jLabelSSSContrib = new javax.swing.JLabel();
        jLabelPhilHealthContrib = new javax.swing.JLabel();
        jLabelPagIBIGContrib = new javax.swing.JLabel();
        jTextFieldSSSContrib = new javax.swing.JTextField();
        jTextFieldPhilHealthContrib = new javax.swing.JTextField();
        jTextFieldPagIBIGContrib = new javax.swing.JTextField();
        jLabelTax = new javax.swing.JLabel();
        jTextFieldTax = new javax.swing.JTextField();
        jPanelAllowances = new javax.swing.JPanel();
        jLabelSSSContrib1 = new javax.swing.JLabel();
        jLabelPhilHealthContrib1 = new javax.swing.JLabel();
        jLabelPagIBIGContrib1 = new javax.swing.JLabel();
        jTextFieldRiceAllowance = new javax.swing.JTextField();
        jTextFieldPhoneAllowance = new javax.swing.JTextField();
        jTextFieldClothingAllowance = new javax.swing.JTextField();
        jPanelSalaryMonth = new javax.swing.JPanel();
        jComboMonth = new javax.swing.JComboBox<>();
        jLabelCurrentYear = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelCalculateSalary = new javax.swing.JPanel();
        jLabelGrossSalary = new javax.swing.JLabel();
        jLabelTotalAllowance = new javax.swing.JLabel();
        jLabelTotalDeduction = new javax.swing.JLabel();
        jLabelNetSalary = new javax.swing.JLabel();
        jTextFieldGrossSalary = new javax.swing.JTextField();
        jTextFieldTotalAllowance = new javax.swing.JTextField();
        jTextFieldTotalDeduction = new javax.swing.JTextField();
        jTextFieldNetSalary = new javax.swing.JTextField();
        jLabelBasicSalary = new javax.swing.JLabel();
        jTextFieldBasicSalary = new javax.swing.JTextField();
        jLabelHourlyRate = new javax.swing.JLabel();
        jTextFieldHourlyRate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));

        jPanelHeader.setBackground(new java.awt.Color(99, 93, 255));

        labelCompany.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelCompany.setForeground(new java.awt.Color(255, 255, 255));
        labelCompany.setText("MotorPH");

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGO_icon.png"))); // NOI18N
        labelLogo.setText("jLabel1");
        labelLogo.setMaximumSize(new java.awt.Dimension(172, 119));
        labelLogo.setMinimumSize(new java.awt.Dimension(172, 119));
        labelLogo.setPreferredSize(new java.awt.Dimension(172, 192));

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFooter.setBackground(new java.awt.Color(99, 93, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Office Hours: 8:00AM - 5:00PM");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Office Address: 5th Flr., The World Center #330 Sen. Gil Puyat Ave., Makati City, Manila, Philippines");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Office Phone Number: +63-2-754-7000");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Office Email: support@motorph.com");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Group 1");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Section : A1101");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("MO-IT103 - Computer Programming 2");

        javax.swing.GroupLayout jPanelFooterLayout = new javax.swing.GroupLayout(jPanelFooter);
        jPanelFooter.setLayout(jPanelFooterLayout);
        jPanelFooterLayout.setHorizontalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFooterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(396, 396, 396)
                            .addComponent(jLabel11))
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(687, 687, 687)
                            .addComponent(jLabel21))
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(574, 574, 574)
                            .addComponent(jLabel18)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelFooterLayout.setVerticalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
            .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFooterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHome.setText("HOME");
        jButtonHome.setMaximumSize(new java.awt.Dimension(150, 50));
        jButtonHome.setMinimumSize(new java.awt.Dimension(150, 50));
        jButtonHome.setPreferredSize(new java.awt.Dimension(150, 50));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(232, 19, 19));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("LOGOUT");
        jButtonLogout.setMaximumSize(new java.awt.Dimension(150, 50));
        jButtonLogout.setMinimumSize(new java.awt.Dimension(150, 50));
        jButtonLogout.setPreferredSize(new java.awt.Dimension(150, 50));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonPayroll1.setBackground(new java.awt.Color(99, 93, 255));
        jButtonPayroll1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPayroll1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPayroll1.setText("PAYROLL SUMMARY");
        jButtonPayroll1.setMaximumSize(new java.awt.Dimension(200, 50));
        jButtonPayroll1.setMinimumSize(new java.awt.Dimension(200, 50));
        jButtonPayroll1.setPreferredSize(new java.awt.Dimension(200, 50));
        jButtonPayroll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayroll1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNavHomeLayout = new javax.swing.GroupLayout(jPanelNavHome);
        jPanelNavHome.setLayout(jPanelNavHomeLayout);
        jPanelNavHomeLayout.setHorizontalGroup(
            jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavHomeLayout.createSequentialGroup()
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1274, Short.MAX_VALUE))
        );
        jPanelNavHomeLayout.setVerticalGroup(
            jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavHomeLayout.createSequentialGroup()
                .addGroup(jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPayroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEmpProfile.setBackground(new java.awt.Color(223, 227, 232));

        jLabelLastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLastName.setText("Last Name:");
        jLabelLastName.setMaximumSize(new java.awt.Dimension(48, 16));
        jLabelLastName.setMinimumSize(new java.awt.Dimension(48, 16));
        jLabelLastName.setPreferredSize(new java.awt.Dimension(48, 16));

        jTextField1LastName.setMaximumSize(new java.awt.Dimension(64, 22));

        jLabelFirstName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFirstName.setText("First Name:");
        jLabelFirstName.setMaximumSize(new java.awt.Dimension(48, 16));
        jLabelFirstName.setMinimumSize(new java.awt.Dimension(48, 16));
        jLabelFirstName.setPreferredSize(new java.awt.Dimension(48, 16));

        jTextField2FirstName.setMaximumSize(new java.awt.Dimension(64, 22));
        jTextField2FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2FirstNameActionPerformed(evt);
            }
        });

        jButtonBackButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBackButton.setText("BACK");
        jButtonBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackButtonActionPerformed(evt);
            }
        });

        jLabel3EmpNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3EmpNo.setText("Emp No.");

        jTextFieldEmpNo.setMaximumSize(new java.awt.Dimension(64, 22));
        jTextFieldEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpNoActionPerformed(evt);
            }
        });

        jLabelPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPhoneNo.setText("Phone No.:");
        jLabelPhoneNo.setMaximumSize(new java.awt.Dimension(48, 16));
        jLabelPhoneNo.setMinimumSize(new java.awt.Dimension(48, 16));
        jLabelPhoneNo.setPreferredSize(new java.awt.Dimension(48, 16));

        jTextFieldPhoneNo.setMaximumSize(new java.awt.Dimension(64, 22));
        jTextFieldPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNoActionPerformed(evt);
            }
        });

        jLabelSSS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSSS.setText("SSS:");
        jLabelSSS.setMaximumSize(new java.awt.Dimension(48, 16));
        jLabelSSS.setMinimumSize(new java.awt.Dimension(48, 16));
        jLabelSSS.setPreferredSize(new java.awt.Dimension(48, 16));

        jTextFieldSSS.setMaximumSize(new java.awt.Dimension(64, 22));
        jTextFieldSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSSSActionPerformed(evt);
            }
        });

        jLabelPhilHealth.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPhilHealth.setText("Phil Health: ");
        jLabelPhilHealth.setMaximumSize(new java.awt.Dimension(48, 16));
        jLabelPhilHealth.setMinimumSize(new java.awt.Dimension(48, 16));
        jLabelPhilHealth.setPreferredSize(new java.awt.Dimension(48, 16));

        jTextFieldPhilHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhilHealthActionPerformed(evt);
            }
        });

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelStatus.setText("Employment Status:");
        jLabelStatus.setMaximumSize(new java.awt.Dimension(48, 16));
        jLabelStatus.setMinimumSize(new java.awt.Dimension(48, 16));
        jLabelStatus.setPreferredSize(new java.awt.Dimension(48, 16));

        jTextFieldStatus.setMaximumSize(new java.awt.Dimension(64, 22));

        jLabelTIN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTIN.setText("TIN #:");
        jLabelTIN.setMaximumSize(new java.awt.Dimension(48, 16));
        jLabelTIN.setMinimumSize(new java.awt.Dimension(48, 16));
        jLabelTIN.setPreferredSize(new java.awt.Dimension(48, 16));

        jTextFieldTIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTINActionPerformed(evt);
            }
        });

        jLabelPagIbig.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPagIbig.setText("PAGIBIG #: ");
        jLabelPagIbig.setMaximumSize(new java.awt.Dimension(48, 16));
        jLabelPagIbig.setMinimumSize(new java.awt.Dimension(48, 16));
        jLabelPagIbig.setPreferredSize(new java.awt.Dimension(48, 16));

        jTextFieldPAGIBIG.setMaximumSize(new java.awt.Dimension(64, 22));
        jTextFieldPAGIBIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPAGIBIGActionPerformed(evt);
            }
        });

        jLabel3Position.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3Position.setText("Employee Position: ");
        jLabel3Position.setMaximumSize(new java.awt.Dimension(48, 16));
        jLabel3Position.setMinimumSize(new java.awt.Dimension(48, 16));
        jLabel3Position.setPreferredSize(new java.awt.Dimension(48, 16));

        jTextFieldPosition.setMaximumSize(new java.awt.Dimension(64, 22));

        javax.swing.GroupLayout jPanelEmpProfileLayout = new javax.swing.GroupLayout(jPanelEmpProfile);
        jPanelEmpProfile.setLayout(jPanelEmpProfileLayout);
        jPanelEmpProfileLayout.setHorizontalGroup(
            jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpProfileLayout.createSequentialGroup()
                                .addComponent(jLabelPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 195, 195))
                            .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEmpProfileLayout.createSequentialGroup()
                                    .addComponent(jLabelSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldSSS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEmpProfileLayout.createSequentialGroup()
                                    .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                                            .addComponent(jLabelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(6, 6, 6))
                                        .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                                            .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                                .addComponent(jLabel3Position, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3EmpNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField1LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField2FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldEmpNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEmpProfileLayout.createSequentialGroup()
                                    .addComponent(jLabelPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEmpProfileLayout.createSequentialGroup()
                                    .addComponent(jLabelTIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(195, 195, 195))
                                .addComponent(jLabelLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPagIbig, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPAGIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButtonBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEmpProfileLayout.setVerticalGroup(
            jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3EmpNo)
                    .addComponent(jTextFieldEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPagIbig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPAGIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBackButton)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        jPanelPayroll.setBackground(new java.awt.Color(255, 255, 255));

        jPanelEmpTimesheet.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Timesheet"));

        jLabelHoursWorked.setText("Hours Worked");

        jLabelOvertimeHours.setText("Overtime hours");

        jLabelUndertimeHours.setText("Undertime hours");

        jTextFieldHoursWorked.setText("00:00:00");
        jTextFieldHoursWorked.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldHoursWorked.setMinimumSize(new java.awt.Dimension(73, 22));

        jTextFieldOvertimeHours.setText("00:00:00");
        jTextFieldOvertimeHours.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldOvertimeHours.setMinimumSize(new java.awt.Dimension(73, 22));

        jTextFieldUndertimeHours.setText("00:00:00");
        jTextFieldUndertimeHours.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldUndertimeHours.setMinimumSize(new java.awt.Dimension(73, 22));

        javax.swing.GroupLayout jPanelEmpTimesheetLayout = new javax.swing.GroupLayout(jPanelEmpTimesheet);
        jPanelEmpTimesheet.setLayout(jPanelEmpTimesheetLayout);
        jPanelEmpTimesheetLayout.setHorizontalGroup(
            jPanelEmpTimesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpTimesheetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpTimesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOvertimeHours, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUndertimeHours, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanelEmpTimesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOvertimeHours, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUndertimeHours, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanelEmpTimesheetLayout.setVerticalGroup(
            jPanelEmpTimesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpTimesheetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpTimesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoursWorked)
                    .addComponent(jTextFieldHoursWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEmpTimesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldOvertimeHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOvertimeHours))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEmpTimesheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUndertimeHours)
                    .addComponent(jTextFieldUndertimeHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDeductions.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deductions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabelSSSContrib.setText("SSS Contribution");

        jLabelPhilHealthContrib.setText("Phil Health");

        jLabelPagIBIGContrib.setText("Pag-IBIG");

        jTextFieldSSSContrib.setText("0.00");
        jTextFieldSSSContrib.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldSSSContrib.setMinimumSize(new java.awt.Dimension(73, 22));

        jTextFieldPhilHealthContrib.setText("0.00");
        jTextFieldPhilHealthContrib.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldPhilHealthContrib.setMinimumSize(new java.awt.Dimension(73, 22));

        jTextFieldPagIBIGContrib.setText("0.00");
        jTextFieldPagIBIGContrib.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldPagIBIGContrib.setMinimumSize(new java.awt.Dimension(73, 22));

        jLabelTax.setText("Tax");

        jTextFieldTax.setText("0.00");
        jTextFieldTax.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldTax.setMinimumSize(new java.awt.Dimension(73, 22));

        javax.swing.GroupLayout jPanelDeductionsLayout = new javax.swing.GroupLayout(jPanelDeductions);
        jPanelDeductions.setLayout(jPanelDeductionsLayout);
        jPanelDeductionsLayout.setHorizontalGroup(
            jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeductionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSSSContrib, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhilHealthContrib, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPagIBIGContrib, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTax, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSSSContrib, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhilHealthContrib, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPagIBIGContrib, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanelDeductionsLayout.setVerticalGroup(
            jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeductionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSSSContrib)
                    .addComponent(jTextFieldSSSContrib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPhilHealthContrib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhilHealthContrib))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPagIBIGContrib)
                    .addComponent(jTextFieldPagIBIGContrib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDeductionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTax)
                    .addComponent(jTextFieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAllowances.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Allowances", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabelSSSContrib1.setText("Rice Allowance");

        jLabelPhilHealthContrib1.setText("Phone Allowance");

        jLabelPagIBIGContrib1.setText("Clothing Allowance");

        jTextFieldRiceAllowance.setText("0.00");
        jTextFieldRiceAllowance.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldRiceAllowance.setMinimumSize(new java.awt.Dimension(73, 22));

        jTextFieldPhoneAllowance.setText("0.00");
        jTextFieldPhoneAllowance.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldPhoneAllowance.setMinimumSize(new java.awt.Dimension(73, 22));

        jTextFieldClothingAllowance.setText("0.00");
        jTextFieldClothingAllowance.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldClothingAllowance.setMinimumSize(new java.awt.Dimension(73, 22));

        javax.swing.GroupLayout jPanelAllowancesLayout = new javax.swing.GroupLayout(jPanelAllowances);
        jPanelAllowances.setLayout(jPanelAllowancesLayout);
        jPanelAllowancesLayout.setHorizontalGroup(
            jPanelAllowancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAllowancesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAllowancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSSSContrib1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhilHealthContrib1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPagIBIGContrib1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAllowancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRiceAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanelAllowancesLayout.setVerticalGroup(
            jPanelAllowancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAllowancesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAllowancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSSSContrib1)
                    .addComponent(jTextFieldRiceAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAllowancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhilHealthContrib1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAllowancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPagIBIGContrib1)
                    .addComponent(jTextFieldClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jPanelSalaryMonth.setBackground(new java.awt.Color(147, 145, 255));

        jComboMonth.setBackground(new java.awt.Color(99, 93, 255));
        jComboMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboMonth.setForeground(new java.awt.Color(255, 255, 255));
        jComboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboMonth.setMaximumSize(new java.awt.Dimension(108, 26));
        jComboMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboMonthItemStateChanged(evt);
            }
        });

        jLabelCurrentYear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCurrentYear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCurrentYear.setText("CurrentYear");
        jLabelCurrentYear.setMaximumSize(new java.awt.Dimension(108, 26));
        jLabelCurrentYear.setMinimumSize(new java.awt.Dimension(108, 26));
        jLabelCurrentYear.setPreferredSize(new java.awt.Dimension(108, 26));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Month");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Year");

        javax.swing.GroupLayout jPanelSalaryMonthLayout = new javax.swing.GroupLayout(jPanelSalaryMonth);
        jPanelSalaryMonth.setLayout(jPanelSalaryMonthLayout);
        jPanelSalaryMonthLayout.setHorizontalGroup(
            jPanelSalaryMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalaryMonthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSalaryMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSalaryMonthLayout.createSequentialGroup()
                        .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSalaryMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSalaryMonthLayout.createSequentialGroup()
                        .addComponent(jLabelCurrentYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(505, 505, 505))
                    .addGroup(jPanelSalaryMonthLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelSalaryMonthLayout.setVerticalGroup(
            jPanelSalaryMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalaryMonthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSalaryMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSalaryMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCurrentYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanelCalculateSalary.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Monthly Salary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 255, 0))); // NOI18N

        jLabelGrossSalary.setText("Gross Salary");

        jLabelTotalAllowance.setText("Total Allowance");

        jLabelTotalDeduction.setText("Total Deduction");

        jLabelNetSalary.setText("Net Salary");

        jTextFieldGrossSalary.setText("0.00");
        jTextFieldGrossSalary.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldGrossSalary.setMinimumSize(new java.awt.Dimension(73, 22));

        jTextFieldTotalAllowance.setText("0.00");
        jTextFieldTotalAllowance.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldTotalAllowance.setMinimumSize(new java.awt.Dimension(73, 22));

        jTextFieldTotalDeduction.setText("0.00");
        jTextFieldTotalDeduction.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldTotalDeduction.setMinimumSize(new java.awt.Dimension(73, 22));

        jTextFieldNetSalary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldNetSalary.setText("0.00");
        jTextFieldNetSalary.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldNetSalary.setMinimumSize(new java.awt.Dimension(73, 22));

        jLabelBasicSalary.setText("Basic Salary");

        jTextFieldBasicSalary.setText("0.00");
        jTextFieldBasicSalary.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldBasicSalary.setMinimumSize(new java.awt.Dimension(73, 22));

        jLabelHourlyRate.setText("Hourly Rate");

        jTextFieldHourlyRate.setText("0.00");
        jTextFieldHourlyRate.setMaximumSize(new java.awt.Dimension(73, 22));
        jTextFieldHourlyRate.setMinimumSize(new java.awt.Dimension(73, 22));

        javax.swing.GroupLayout jPanelCalculateSalaryLayout = new javax.swing.GroupLayout(jPanelCalculateSalary);
        jPanelCalculateSalary.setLayout(jPanelCalculateSalaryLayout);
        jPanelCalculateSalaryLayout.setHorizontalGroup(
            jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculateSalaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCalculateSalaryLayout.createSequentialGroup()
                        .addComponent(jLabelGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCalculateSalaryLayout.createSequentialGroup()
                        .addGroup(jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTotalAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotalDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTotalAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTotalDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCalculateSalaryLayout.createSequentialGroup()
                        .addComponent(jLabelBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCalculateSalaryLayout.createSequentialGroup()
                        .addComponent(jLabelHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanelCalculateSalaryLayout.setVerticalGroup(
            jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalculateSalaryLayout.createSequentialGroup()
                .addGroup(jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBasicSalary)
                    .addComponent(jTextFieldBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHourlyRate)
                    .addComponent(jTextFieldHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCalculateSalaryLayout.createSequentialGroup()
                        .addGroup(jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGrossSalary)
                            .addComponent(jTextFieldGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))
                    .addGroup(jPanelCalculateSalaryLayout.createSequentialGroup()
                        .addGroup(jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalAllowance)
                            .addComponent(jTextFieldTotalAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalDeduction)
                            .addComponent(jTextFieldTotalDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCalculateSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNetSalary)
                            .addComponent(jTextFieldNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jPanelPayrollLayout = new javax.swing.GroupLayout(jPanelPayroll);
        jPanelPayroll.setLayout(jPanelPayrollLayout);
        jPanelPayrollLayout.setHorizontalGroup(
            jPanelPayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPayrollLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSalaryMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPayrollLayout.createSequentialGroup()
                        .addGroup(jPanelPayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelEmpTimesheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDeductions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelAllowances, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelCalculateSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanelPayrollLayout.setVerticalGroup(
            jPanelPayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPayrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSalaryMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAllowances, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEmpTimesheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDeductions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCalculateSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNavHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEmpProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNavHome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEmpProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPayroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* ############ CUSTOM CODE BELOW ############# */
    private void loadWorkHours(int empID, int selectedMonth, int currentYear){
        EmpAttendance ea = new EmpAttendance();
        List<AttendanceTrack> listAttendance = ea.getTimesheetByIDandDate(empID, selectedMonth, currentYear);
        ea.calculateTotalHoursWorked(listAttendance, selectedMonth, currentYear);
        
        //Save the calc hours in different variables for the gross salary calculation
        MinutesWorked = ea.calcMinutesWorked;
        OvertimeMinutes = ea.calcOvertimeMinutes;
        UndertimeMinutes = ea.calcUndertimeMinutes;

        jTextFieldHoursWorked.setText(Long.toString(MinutesWorked/60) + ":" + Long.toString(MinutesWorked%60) + ":00");
        jTextFieldOvertimeHours.setText(Long.toString(OvertimeMinutes/60) + ":" + Long.toString(OvertimeMinutes%60) + ":00");
        jTextFieldUndertimeHours.setText(Long.toString(UndertimeMinutes/60) + ":" + Long.toString(UndertimeMinutes%60) + ":00");
    }

private float calcNetSalary(float gsalary, float totalAllowance, float totalDeduction) {
    float netsal = gsalary + totalAllowance - totalDeduction;
    jTextFieldNetSalary.setText(String.format("%.2f",netsal));
    return netsal;
}    
    
    
    
private float calcGrossSalary(float basicSalary, long hrRate, long minuteWork, long overtimeWork, long undertimeWork){
        float monthlySalary = (float) minuteWork * hrRate;
        float overtimePay = (float) 0.00;
        float undertimeDeduction = (float) 0.00;
        float gs = (float) 0.00;
        
     // Calculated monthly salary using regular minutes worked cannot exceed the basic MOnthly salary. Excess should be charged to overtime Pay.
    if (monthlySalary >= basicSalary){
	monthlySalary = basicSalary;
    }
    
    if (overtimeWork > 0) {
        // This is the Overtime formula based on PH Taxation
        overtimePay = ((OvertimeMinutes / 60) * hourlyRate) / (WorkHoursCalculator.REGULAR_WORK_HOURS);

    } else {
        overtimePay = 0;
    }    

    if (undertimeWork > 0) {
        // This is the Overtime formula based on PH Taxation
        undertimeDeduction = ((OvertimeMinutes / 60) * hourlyRate) / (WorkHoursCalculator.REGULAR_WORK_HOURS);

    } else {
        undertimeDeduction = 0;
    }      

    gs = monthlySalary + overtimePay - undertimeDeduction;
    // Bind the values to the jTextFields
    jTextFieldBasicSalary.setText(String.format("%.2f",monthlySalary));
    jTextFieldHourlyRate.setText(String.format("%.2f",(float) hrRate));
    jTextFieldGrossSalary.setText(String.format("%.2f",gs));

    return gs;
}
    
    private float calcEmpDeductions(int empID, float gsal){
        float td = (float) 0.00;
        try{
        if (empID != 0) {
            BenefitsCalculator calc = new BenefitsCalculator(empID);  
            
            EmpDeductions empDed = calc.CalculateDeductions(gsal);
            // Bind the Deductions to the text fields
            jTextFieldSSSContrib.setText(String.format("%.2f",empDed.getSSS()));
            jTextFieldPhilHealthContrib.setText(String.format("%.2f",empDed.getPhilHealth()));
            jTextFieldPagIBIGContrib.setText(String.format("%.2f",empDed.getPagIBIG()));
            //these are already considered once the total hours are calculated because there will be less hours worked if the employee went on VL or got late.
            // jTextFieldTardiness
            // jLabelAbsences
            jTextFieldTax.setText(String.format("%.2f",empDed.getWithholdingTax()));
            jTextFieldTotalDeduction.setText(String.format("%.2f",empDed.getTotalDeductions()));
            td = empDed.getTotalDeductions();
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error in retrieving info: " + e.getMessage());
        }
        
        return td;
    }    
    
    private float calcEmpAllowances(int empID){
        float ta = (float) 0.00;
        
        try{
        if (empID != 0) {
            BenefitsCalculator calc = new BenefitsCalculator(empID);  

            EmpAllowances empAllowance = calc.GetAllEmpAllowances(empID);
            // Bind the Deductions to the text fields
            jTextFieldRiceAllowance.setText(String.format("%.2f",empAllowance.getRiceAllowance()));
            jTextFieldPhoneAllowance.setText(String.format("%.2f",empAllowance.getPhoneAllowance()));
            jTextFieldClothingAllowance.setText(String.format("%.2f",empAllowance.getClothingAllowance()));
            jTextFieldTotalAllowance.setText(String.format("%.2f",empAllowance.getTotalAllowance()));
            
            jTextFieldBasicSalary.setText(String.format("%.2f",empAllowance.getBasicSalary()));
            jTextFieldHourlyRate.setText(String.format("%.2f",empAllowance.getHourlyRate()));
 
            basicSalary = empAllowance.getBasicSalary();
            hourlyRate = (long) empAllowance.getHourlyRate();
            
            ta = empAllowance.getTotalAllowance();
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error in retrieving info: " + e.getMessage());
        }
        
        return ta;
    }
    
    private void loadEmpDetails(int empID) {
        if (empID != 0) {
            // Retrieve the Employee ID
            EmpActions eactSelectedEmp = new EmpActions();
            EmpDetails eDetails = eactSelectedEmp.returnAllDataToTextField(empID);
            jTextFieldEmpNo.setText(String.valueOf(eDetails.getId()));
            jTextFieldStatus.setText(eDetails.getSatus());
            jTextField1LastName.setText(eDetails.getLastName());
            jTextField2FirstName.setText(eDetails.getFirstName());
            jTextFieldPhoneNo.setText(eDetails.getPhoneNumber());
            jTextFieldSSS.setText(eDetails.getSSS());
            jTextFieldPhilHealth.setText(eDetails.getPhilHealth());
            jTextFieldTIN.setText(eDetails.getTIN());
            jTextFieldPAGIBIG.setText(eDetails.getPagIbig());
            jTextFieldPosition.setText(eDetails.getPosition());
            
            jTextFieldEmpNo.setEditable(false);
            jTextFieldStatus.setEditable(false);
            jTextField1LastName.setEditable(false);
            jTextField2FirstName.setEditable(false);
            jTextFieldPhoneNo.setEditable(false);
            jTextFieldSSS.setEditable(false);
            jTextFieldPhilHealth.setEditable(false);
            jTextFieldTIN.setEditable(false);
            jTextFieldPAGIBIG.setEditable(false);
            jTextFieldPosition.setEditable(false); 
            
        }
    }
    
    
    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        JFrameHome FrameHome = new JFrameHome();
        FrameHome.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        JFrameLogin FrameLogin = new JFrameLogin();
        FrameLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed
    
    
    private void jButtonPayroll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayroll1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPayroll1ActionPerformed

    private void jTextFieldPAGIBIGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPAGIBIGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPAGIBIGActionPerformed

    private void jTextFieldTINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTINActionPerformed

    private void jTextFieldPhilHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhilHealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhilHealthActionPerformed

    private void jTextFieldSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSSSActionPerformed

    private void jTextFieldPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNoActionPerformed

    private void jTextFieldEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpNoActionPerformed

    private void jButtonBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackButtonActionPerformed

        JFrameEmpInfo FrameEmpInfo = new JFrameEmpInfo();
        FrameEmpInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackButtonActionPerformed

    private void jTextField2FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FirstNameActionPerformed

    private void jComboMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboMonthItemStateChanged

        // Get the basic salary and hourly rate
        this.totalAllowances = calcEmpAllowances(this.id);
        
        // Get the calculated hours (or minutes) worked for the chosen month
        // Added 1 to the SelectedIndex because arrays start with 0.
        loadWorkHours(this.id, jComboMonth.getSelectedIndex()+1, currentYear);

        // Get the Gross Salary
        this.grossSalary = calcGrossSalary(basicSalary, hourlyRate, MinutesWorked, OvertimeMinutes, UndertimeMinutes);
        
        // Get the Deductions
        this.totalDeductions = calcEmpDeductions(this.id, this.grossSalary);
        
        // Get the Net Salary
        this.netSalary = calcNetSalary(this.grossSalary, this.totalAllowances, this.totalDeductions);                
    }//GEN-LAST:event_jComboMonthItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEmpPayroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackButton;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPayroll1;
    private javax.swing.JComboBox<String> jComboMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3EmpNo;
    private javax.swing.JLabel jLabel3Position;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBasicSalary;
    private javax.swing.JLabel jLabelCurrentYear;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelGrossSalary;
    private javax.swing.JLabel jLabelHourlyRate;
    private javax.swing.JLabel jLabelHoursWorked;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelNetSalary;
    private javax.swing.JLabel jLabelOvertimeHours;
    private javax.swing.JLabel jLabelPagIBIGContrib;
    private javax.swing.JLabel jLabelPagIBIGContrib1;
    private javax.swing.JLabel jLabelPagIbig;
    private javax.swing.JLabel jLabelPhilHealth;
    private javax.swing.JLabel jLabelPhilHealthContrib;
    private javax.swing.JLabel jLabelPhilHealthContrib1;
    private javax.swing.JLabel jLabelPhoneNo;
    private javax.swing.JLabel jLabelSSS;
    private javax.swing.JLabel jLabelSSSContrib;
    private javax.swing.JLabel jLabelSSSContrib1;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTIN;
    private javax.swing.JLabel jLabelTax;
    private javax.swing.JLabel jLabelTotalAllowance;
    private javax.swing.JLabel jLabelTotalDeduction;
    private javax.swing.JLabel jLabelUndertimeHours;
    private javax.swing.JPanel jPanelAllowances;
    private javax.swing.JPanel jPanelCalculateSalary;
    private javax.swing.JPanel jPanelDeductions;
    private javax.swing.JPanel jPanelEmpProfile;
    private javax.swing.JPanel jPanelEmpTimesheet;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelNavHome;
    private javax.swing.JPanel jPanelPayroll;
    private javax.swing.JPanel jPanelSalaryMonth;
    private javax.swing.JTextField jTextField1LastName;
    private javax.swing.JTextField jTextField2FirstName;
    private javax.swing.JTextField jTextFieldBasicSalary;
    private javax.swing.JTextField jTextFieldClothingAllowance;
    private javax.swing.JTextField jTextFieldEmpNo;
    private javax.swing.JTextField jTextFieldGrossSalary;
    private javax.swing.JTextField jTextFieldHourlyRate;
    private javax.swing.JTextField jTextFieldHoursWorked;
    private javax.swing.JTextField jTextFieldNetSalary;
    private javax.swing.JTextField jTextFieldOvertimeHours;
    private javax.swing.JTextField jTextFieldPAGIBIG;
    private javax.swing.JTextField jTextFieldPagIBIGContrib;
    private javax.swing.JTextField jTextFieldPhilHealth;
    private javax.swing.JTextField jTextFieldPhilHealthContrib;
    private javax.swing.JTextField jTextFieldPhoneAllowance;
    private javax.swing.JTextField jTextFieldPhoneNo;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldRiceAllowance;
    private javax.swing.JTextField jTextFieldSSS;
    private javax.swing.JTextField jTextFieldSSSContrib;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldTIN;
    private javax.swing.JTextField jTextFieldTax;
    private javax.swing.JTextField jTextFieldTotalAllowance;
    private javax.swing.JTextField jTextFieldTotalDeduction;
    private javax.swing.JTextField jTextFieldUndertimeHours;
    private java.awt.Label labelCompany;
    private javax.swing.JLabel labelLogo;
    // End of variables declaration//GEN-END:variables
}
