/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.screens;
import com.baseActions.EmpAttendance;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author JD Morales
 */
public class JFrameHome extends javax.swing.JFrame {
    private int empID;
    private String designation;
    private boolean isCheckedIn = false;    
    private boolean isCheckedOut = false;    

    /**
     * Creates new form JavaTabs
     * @param paramEID is the employeeID
     * @param paramdesignation can either be Admin or Employee
     */
    public JFrameHome(int paramEID, String paramdesignation) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        currentDate();
        time();        
        
        this.empID = paramEID;
        this.designation = paramdesignation;
        jLabelEmpNo.setText("Employee ID: " + String.valueOf(EmpAttendance.UserID));
        jLabelEmpName.setText(EmpAttendance.UserFirstName + " " + EmpAttendance.UserLastName);
        jLabelEmpPosition.setText(EmpAttendance.UserPosition);
    }

    public JFrameHome() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        
        currentDate();
        time();

        this.empID = EmpAttendance.UserID;
        this.designation = EmpAttendance.UserDesignation;
        jLabelEmpNo.setText("Employee ID: " + String.valueOf(EmpAttendance.UserID));
        jLabelEmpName.setText(EmpAttendance.UserFirstName + " " + EmpAttendance.UserLastName);
        jLabelEmpPosition.setText(EmpAttendance.UserPosition);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        labelCompany = new java.awt.Label();
        labelLogo = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanelNavHome = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonTimesheet = new javax.swing.JButton();
        jButtonEmpInfo = new javax.swing.JButton();
        jButtonLeaveApp = new javax.swing.JButton();
        jPanelEmpProfile = new javax.swing.JPanel();
        jPanelHomeEmployee = new javax.swing.JPanel();
        jLabelEmpName = new javax.swing.JLabel();
        jLabelEmpNo = new javax.swing.JLabel();
        jLabelEmpPosition = new javax.swing.JLabel();
        jPanelTimecard = new javax.swing.JPanel();
        jPanelHomeCurrentTime = new javax.swing.JPanel();
        jLabelHomeCurrentTime = new javax.swing.JLabel();
        jPanelHomeTimezone = new javax.swing.JPanel();
        jLabelHomeTIMEZONE = new javax.swing.JLabel();
        jPanelHomeCurrentTime1 = new javax.swing.JPanel();
        jLabel6Time = new javax.swing.JLabel();
        jPanelHomeCurrentTime2 = new javax.swing.JPanel();
        jLabelHomeCurrentTime2 = new javax.swing.JLabel();
        jPanelHomeTimezone1 = new javax.swing.JPanel();
        jLabelHomeTIMEZONE1 = new javax.swing.JLabel();
        jLabelHomeTimeOut = new javax.swing.JLabel();
        jLabelHomeTimeIn = new javax.swing.JLabel();
        jButton2CheckIN = new javax.swing.JButton();
        jButton1CheckOUT = new javax.swing.JButton();
        jLabel17CheckIN1 = new javax.swing.JLabel();
        jLabel8CheckOUT = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6Date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));

        jPanelHeader.setBackground(new java.awt.Color(99, 93, 255));

        labelCompany.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelCompany.setForeground(new java.awt.Color(255, 255, 255));
        labelCompany.setText("MotorPH");

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGO_icon.png"))); // NOI18N
        labelLogo.setText("jLabel1");
        labelLogo.setMaximumSize(new java.awt.Dimension(172, 119));
        labelLogo.setMinimumSize(new java.awt.Dimension(172, 119));
        labelLogo.setPreferredSize(new java.awt.Dimension(172, 192));

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFooter.setBackground(new java.awt.Color(99, 93, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Office Hours: 8:00AM - 5:00PM");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Office Address: 5th Flr., The World Center #330 Sen. Gil Puyat Ave., Makati City, Manila, Philippines");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Office Phone Number: +63-2-754-7000");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Office Email: support@motorph.com");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Group 1");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Section : A1101");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("MO-IT103 - Computer Programming 2");

        javax.swing.GroupLayout jPanelFooterLayout = new javax.swing.GroupLayout(jPanelFooter);
        jPanelFooter.setLayout(jPanelFooterLayout);
        jPanelFooterLayout.setHorizontalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFooterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(396, 396, 396)
                            .addComponent(jLabel11))
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(687, 687, 687)
                            .addComponent(jLabel21))
                        .addGroup(jPanelFooterLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(574, 574, 574)
                            .addComponent(jLabel18)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelFooterLayout.setVerticalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
            .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFooterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHome.setText("HOME");
        jButtonHome.setMaximumSize(new java.awt.Dimension(175, 50));
        jButtonHome.setMinimumSize(new java.awt.Dimension(175, 50));
        jButtonHome.setPreferredSize(new java.awt.Dimension(175, 50));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(232, 19, 19));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("LOGOUT");
        jButtonLogout.setMaximumSize(new java.awt.Dimension(150, 50));
        jButtonLogout.setMinimumSize(new java.awt.Dimension(150, 50));
        jButtonLogout.setPreferredSize(new java.awt.Dimension(150, 50));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonTimesheet.setBackground(new java.awt.Color(99, 93, 255));
        jButtonTimesheet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTimesheet.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimesheet.setText("TIMESHEET");
        jButtonTimesheet.setMaximumSize(new java.awt.Dimension(175, 50));
        jButtonTimesheet.setMinimumSize(new java.awt.Dimension(175, 50));
        jButtonTimesheet.setPreferredSize(new java.awt.Dimension(175, 50));
        jButtonTimesheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimesheetActionPerformed(evt);
            }
        });

        jButtonEmpInfo.setBackground(new java.awt.Color(99, 93, 255));
        jButtonEmpInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEmpInfo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmpInfo.setText("EMPLOYEE INFORMATION");
        jButtonEmpInfo.setMaximumSize(new java.awt.Dimension(250, 50));
        jButtonEmpInfo.setMinimumSize(new java.awt.Dimension(250, 50));
        jButtonEmpInfo.setPreferredSize(new java.awt.Dimension(250, 50));
        jButtonEmpInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpInfoActionPerformed(evt);
            }
        });

        jButtonLeaveApp.setBackground(new java.awt.Color(99, 93, 255));
        jButtonLeaveApp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLeaveApp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLeaveApp.setText("LEAVE APPLICATION");
        jButtonLeaveApp.setMaximumSize(new java.awt.Dimension(200, 50));
        jButtonLeaveApp.setMinimumSize(new java.awt.Dimension(200, 50));
        jButtonLeaveApp.setPreferredSize(new java.awt.Dimension(200, 50));
        jButtonLeaveApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaveAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNavHomeLayout = new javax.swing.GroupLayout(jPanelNavHome);
        jPanelNavHome.setLayout(jPanelNavHomeLayout);
        jPanelNavHomeLayout.setHorizontalGroup(
            jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavHomeLayout.createSequentialGroup()
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEmpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLeaveApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanelNavHomeLayout.setVerticalGroup(
            jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavHomeLayout.createSequentialGroup()
                .addGroup(jPanelNavHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEmpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLeaveApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEmpProfile.setBackground(new java.awt.Color(255, 255, 255));

        jPanelHomeEmployee.setBackground(new java.awt.Color(99, 93, 255));
        jPanelHomeEmployee.setForeground(new java.awt.Color(255, 255, 255));

        jLabelEmpName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmpName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmpName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpName.setText("test");

        javax.swing.GroupLayout jPanelHomeEmployeeLayout = new javax.swing.GroupLayout(jPanelHomeEmployee);
        jPanelHomeEmployee.setLayout(jPanelHomeEmployeeLayout);
        jPanelHomeEmployeeLayout.setHorizontalGroup(
            jPanelHomeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeEmployeeLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabelEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanelHomeEmployeeLayout.setVerticalGroup(
            jPanelHomeEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeEmployeeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelEmpName)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabelEmpNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmpNo.setText("test");

        jLabelEmpPosition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmpPosition.setText("test");

        javax.swing.GroupLayout jPanelEmpProfileLayout = new javax.swing.GroupLayout(jPanelEmpProfile);
        jPanelEmpProfile.setLayout(jPanelEmpProfileLayout);
        jPanelEmpProfileLayout.setHorizontalGroup(
            jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpProfileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelHomeEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                        .addGroup(jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabelEmpNo))
                            .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabelEmpPosition)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelEmpProfileLayout.setVerticalGroup(
            jPanelEmpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpProfileLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabelEmpNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelHomeEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmpPosition)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTimecard.setBackground(new java.awt.Color(255, 255, 255));

        jPanelHomeCurrentTime.setBackground(new java.awt.Color(99, 93, 255));
        jPanelHomeCurrentTime.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHomeCurrentTime.setMaximumSize(new java.awt.Dimension(200, 50));
        jPanelHomeCurrentTime.setMinimumSize(new java.awt.Dimension(200, 50));
        jPanelHomeCurrentTime.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabelHomeCurrentTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHomeCurrentTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHomeCurrentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHomeCurrentTime.setText("CURRENT TIME");

        javax.swing.GroupLayout jPanelHomeCurrentTimeLayout = new javax.swing.GroupLayout(jPanelHomeCurrentTime);
        jPanelHomeCurrentTime.setLayout(jPanelHomeCurrentTimeLayout);
        jPanelHomeCurrentTimeLayout.setHorizontalGroup(
            jPanelHomeCurrentTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeCurrentTimeLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelHomeCurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHomeCurrentTimeLayout.setVerticalGroup(
            jPanelHomeCurrentTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeCurrentTimeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelHomeCurrentTime)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelHomeTimezone.setBackground(new java.awt.Color(99, 93, 255));
        jPanelHomeTimezone.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHomeTimezone.setMaximumSize(new java.awt.Dimension(200, 50));
        jPanelHomeTimezone.setMinimumSize(new java.awt.Dimension(200, 50));
        jPanelHomeTimezone.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabelHomeTIMEZONE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHomeTIMEZONE.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHomeTIMEZONE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHomeTIMEZONE.setText("TIMEZONE");

        javax.swing.GroupLayout jPanelHomeTimezoneLayout = new javax.swing.GroupLayout(jPanelHomeTimezone);
        jPanelHomeTimezone.setLayout(jPanelHomeTimezoneLayout);
        jPanelHomeTimezoneLayout.setHorizontalGroup(
            jPanelHomeTimezoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeTimezoneLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabelHomeTIMEZONE, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHomeTimezoneLayout.setVerticalGroup(
            jPanelHomeTimezoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeTimezoneLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelHomeTIMEZONE)
                .addGap(14, 14, 14))
        );

        jPanelHomeCurrentTime1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHomeCurrentTime1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelHomeCurrentTime1.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHomeCurrentTime1.setMaximumSize(new java.awt.Dimension(200, 50));
        jPanelHomeCurrentTime1.setMinimumSize(new java.awt.Dimension(200, 50));

        jLabel6Time.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6Time.setText("hh:mm:ss");

        javax.swing.GroupLayout jPanelHomeCurrentTime1Layout = new javax.swing.GroupLayout(jPanelHomeCurrentTime1);
        jPanelHomeCurrentTime1.setLayout(jPanelHomeCurrentTime1Layout);
        jPanelHomeCurrentTime1Layout.setHorizontalGroup(
            jPanelHomeCurrentTime1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeCurrentTime1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6Time, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHomeCurrentTime1Layout.setVerticalGroup(
            jPanelHomeCurrentTime1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeCurrentTime1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6Time)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelHomeCurrentTime2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHomeCurrentTime2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelHomeCurrentTime2.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHomeCurrentTime2.setMaximumSize(new java.awt.Dimension(200, 50));
        jPanelHomeCurrentTime2.setMinimumSize(new java.awt.Dimension(200, 50));

        jLabelHomeCurrentTime2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHomeCurrentTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHomeCurrentTime2.setText("(GMT+8) MANILA, PHILIPPINES");

        javax.swing.GroupLayout jPanelHomeCurrentTime2Layout = new javax.swing.GroupLayout(jPanelHomeCurrentTime2);
        jPanelHomeCurrentTime2.setLayout(jPanelHomeCurrentTime2Layout);
        jPanelHomeCurrentTime2Layout.setHorizontalGroup(
            jPanelHomeCurrentTime2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeCurrentTime2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelHomeCurrentTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHomeCurrentTime2Layout.setVerticalGroup(
            jPanelHomeCurrentTime2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeCurrentTime2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelHomeCurrentTime2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelHomeTimezone1.setBackground(new java.awt.Color(99, 93, 255));
        jPanelHomeTimezone1.setForeground(new java.awt.Color(255, 255, 255));
        jPanelHomeTimezone1.setMaximumSize(new java.awt.Dimension(200, 50));
        jPanelHomeTimezone1.setMinimumSize(new java.awt.Dimension(200, 50));

        jLabelHomeTIMEZONE1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHomeTIMEZONE1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHomeTIMEZONE1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHomeTIMEZONE1.setText("EMPLOYEE TIME CARD");

        javax.swing.GroupLayout jPanelHomeTimezone1Layout = new javax.swing.GroupLayout(jPanelHomeTimezone1);
        jPanelHomeTimezone1.setLayout(jPanelHomeTimezone1Layout);
        jPanelHomeTimezone1Layout.setHorizontalGroup(
            jPanelHomeTimezone1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeTimezone1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabelHomeTIMEZONE1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHomeTimezone1Layout.setVerticalGroup(
            jPanelHomeTimezone1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeTimezone1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelHomeTIMEZONE1)
                .addGap(14, 14, 14))
        );

        jLabelHomeTimeOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHomeTimeOut.setText("TIME-OUT:");

        jLabelHomeTimeIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHomeTimeIn.setText("TIME-IN:");

        jButton2CheckIN.setBackground(new java.awt.Color(51, 204, 0));
        jButton2CheckIN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2CheckIN.setForeground(new java.awt.Color(255, 255, 255));
        jButton2CheckIN.setText("IN");
        jButton2CheckIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CheckINActionPerformed(evt);
            }
        });

        jButton1CheckOUT.setBackground(new java.awt.Color(153, 0, 0));
        jButton1CheckOUT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1CheckOUT.setForeground(new java.awt.Color(255, 255, 255));
        jButton1CheckOUT.setText("OUT");
        jButton1CheckOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CheckOUTActionPerformed(evt);
            }
        });

        jLabel17CheckIN1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel17CheckIN1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17CheckIN1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17CheckIN1.setText("You have not timed in yet.");
        jLabel17CheckIN1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel17CheckIN1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel8CheckOUT.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8CheckOUT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8CheckOUT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8CheckOUT.setText("You have not timed out yet.");
        jLabel8CheckOUT.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel8CheckOUT.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6Date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6Date.setText("jLabel6");
        jPanel12.add(jLabel6Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        javax.swing.GroupLayout jPanelTimecardLayout = new javax.swing.GroupLayout(jPanelTimecard);
        jPanelTimecard.setLayout(jPanelTimecardLayout);
        jPanelTimecardLayout.setHorizontalGroup(
            jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimecardLayout.createSequentialGroup()
                .addGroup(jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTimecardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelHomeTimezone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelTimecardLayout.createSequentialGroup()
                                .addGroup(jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelHomeCurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelHomeTimezone, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelHomeCurrentTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanelHomeCurrentTime2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanelTimecardLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTimecardLayout.createSequentialGroup()
                                .addComponent(jLabelHomeTimeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17CheckIN1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTimecardLayout.createSequentialGroup()
                                .addComponent(jLabelHomeTimeOut)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8CheckOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1CheckOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2CheckIN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTimecardLayout.setVerticalGroup(
            jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimecardLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHomeCurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelHomeCurrentTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelHomeTimezone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelHomeCurrentTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelHomeTimezone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHomeTimeIn)
                    .addComponent(jLabel17CheckIN1)
                    .addComponent(jButton2CheckIN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTimecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHomeTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1CheckOUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8CheckOUT, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNavHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEmpProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTimecard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNavHome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEmpProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTimecard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* ############ CUSTOM CODE BELOW ############# */
public void currentDate(){
        
        Calendar cal = new GregorianCalendar();
        SimpleDateFormat monthFormat = new SimpleDateFormat("MMMM");
        String month = monthFormat.format(cal.getTime());
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        jLabel6Date.setText(month + "  " + day + " , " + year);
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR_OF_DAY);
        
                       
    }
    Timer t;
    SimpleDateFormat st;
    
    public void time() {
        t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                st = new SimpleDateFormat("hh:mm:ss a");
                String tt = st.format(dt);
                jLabel6Time.setText(tt);
            }
        });
        t.start();
    }    
    
    
    
    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        JFrameLogin FrameLogin = new JFrameLogin();
        FrameLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed
    
    
    private void jButton2CheckINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CheckINActionPerformed
        if (isCheckedIn) {
            JOptionPane.showMessageDialog(null, "You are already timed in for today.");
            return;
        }

        Date currentDate = GregorianCalendar.getInstance().getTime();
        DateFormat df = DateFormat.getDateInstance();

        String dateString = df.format(currentDate);
        Date parsedDate;
        try {
            parsedDate = df.parse(dateString);
        } catch (ParseException e) {
            e.printStackTrace(); // Handle the exception appropriately
            return; // or do something else to handle the error
        }

        int value = EmpAttendance.UserID;
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String timeString = sdf.format(d);

        // Check if the user has already checked in for the current date
        boolean alreadyCheckedIn = EmpAttendance.hasCheckedIn(value, parsedDate, Time.valueOf(timeString));
        if (alreadyCheckedIn) {
            JOptionPane.showMessageDialog(null, "You are already timed in for today.");
            isCheckedIn = true; // Update check-in status
        } else {
            // Proceed to insert log entry
            Date reg = parsedDate;
            Time reg1 = Time.valueOf(timeString);
            jLabel17CheckIN1.setText(timeString);
            EmpAttendance.saveTimeInToDatabase(reg, reg1);
            isCheckedIn = true; // Update check-in status
        }
    }//GEN-LAST:event_jButton2CheckINActionPerformed

    private void jButton1CheckOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CheckOUTActionPerformed

        if (isCheckedOut) {
            JOptionPane.showMessageDialog(null, "You are already timed out for today.");
            return;
        }

        Date currentDate = GregorianCalendar.getInstance().getTime();
        DateFormat df = DateFormat.getDateInstance();

        String dateString = df.format(currentDate);
        Date parsedDate;
        try {
            parsedDate = df.parse(dateString);
        } catch (ParseException e) {
            e.printStackTrace(); // Handle the exception appropriately
            return; // or do something else to handle the error
        }

        int value = EmpAttendance.UserID;
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String timeString = sdf.format(d);

        // Check if the user has already checked out for the current date
        boolean alreadyCheckedOut = EmpAttendance.hasCheckedOut(value, parsedDate, Time.valueOf(timeString));
        if (alreadyCheckedOut) {
            JOptionPane.showMessageDialog(null, "You are already timed out for today.");
            isCheckedOut = true; // Update check-out status
        } else {
            // Proceed to insert log entry
            Date reg = parsedDate;
            Time reg1 = Time.valueOf(timeString);
            jLabel8CheckOUT.setText(timeString);
            EmpAttendance.saveTimeOutToDatabase(reg, reg1);
            isCheckedOut = true; // Update check-out status

        }
    }//GEN-LAST:event_jButton1CheckOUTActionPerformed

    private void jButtonTimesheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimesheetActionPerformed
        // TODO add your handling code here:
        new JFrameTimesheet().setVisible(true);
        this.dispose();         
    }//GEN-LAST:event_jButtonTimesheetActionPerformed

    private void jButtonEmpInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpInfoActionPerformed
        // TODO add your handling code here:
        new JFrameEmpInfo(empID, designation).setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jButtonEmpInfoActionPerformed

    private void jButtonLeaveAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaveAppActionPerformed
        // TODO add your handling code here:
        new JFrameLeaveApplication().setVisible(true);
        this.dispose();         
    }//GEN-LAST:event_jButtonLeaveAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1CheckOUT;
    private javax.swing.JButton jButton2CheckIN;
    private javax.swing.JButton jButtonEmpInfo;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLeaveApp;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonTimesheet;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17CheckIN1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6Date;
    private javax.swing.JLabel jLabel6Time;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8CheckOUT;
    private javax.swing.JLabel jLabelEmpName;
    private javax.swing.JLabel jLabelEmpNo;
    private javax.swing.JLabel jLabelEmpPosition;
    private javax.swing.JLabel jLabelHomeCurrentTime;
    private javax.swing.JLabel jLabelHomeCurrentTime2;
    private javax.swing.JLabel jLabelHomeTIMEZONE;
    private javax.swing.JLabel jLabelHomeTIMEZONE1;
    private javax.swing.JLabel jLabelHomeTimeIn;
    private javax.swing.JLabel jLabelHomeTimeOut;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanelEmpProfile;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelHomeCurrentTime;
    private javax.swing.JPanel jPanelHomeCurrentTime1;
    private javax.swing.JPanel jPanelHomeCurrentTime2;
    private javax.swing.JPanel jPanelHomeEmployee;
    private javax.swing.JPanel jPanelHomeTimezone;
    private javax.swing.JPanel jPanelHomeTimezone1;
    private javax.swing.JPanel jPanelNavHome;
    private javax.swing.JPanel jPanelTimecard;
    private java.awt.Label labelCompany;
    private javax.swing.JLabel labelLogo;
    // End of variables declaration//GEN-END:variables
}
